name: Release
on:
  workflow_dispatch:
    inputs:
      tag:
        type: choice
        description: Tag
        required: true
        options:
          - beta
          - latest
      bump:
        type: choice
        description: Bump level
        required: true
        options:
          - patch
          - minor
          - major

#  pull_request:
#    branches:
#      - develop
#    paths:
#      - .github/workflows/release.yaml
#      - src/**
#      - bin/**
#      - yarn.lock

jobs:
  build-publish:
    name: Build & publish
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Write npm credentials
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v3
        id: yarn-cache
        env:
          cache-name: subsquid-cli
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-${{ env.cache-name }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-yarn-

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build

      - name: Release It
        run: |
          if [[ "${{ github.event.inputs.tag }}" == "beta" ]]; then
            yarn release-it ${{ github.event.inputs.bump }} --preRelease=beta
          else
            yarn release-it ${{ github.event.inputs.bump }}
          fi
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
      
      - name: Gen Formula
        run: |
          yarn gen:formula

      - name: Upload Formula
        uses: actions/upload-artifact@v3
        with:
          name: sqd_formula
          path: sqd.rb
          retention-days: 5

  update-brew:
    name: Homebrew
    runs-on: ubuntu-latest
    steps:
      - name: Checkout subsquid/homebrew-cli
        uses: actions/checkout@v3
        with:
          repository: subsquid/homebrew-cli
          ref: 'master'
          token: ${{ github.token }}
          
      - name: Download Formula
        uses: actions/download-artifact@v3
        with:
          name: sqd_formula
      
      - name: Update Homebrew Repo
        run: |
          if [[ "${{ github.event.inputs.tag }}" == "beta" ]]; then
            mv sqd.rb ./homebrew/Formula/sqd@beta.rb
          else
            mv sqd.rb ./homebrew/Formula/sqd.rb
          fi
          git add ./Formula/*
          git commit -m "chore: release"
          git push